# name: Static prod deploy

name: Static prod deploy

on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob sync --account-name 'boardflareaddins' -c 'functions/prod' -s './notebooks' --delete-destination true --sas-token '${{ secrets.CONTAINER_SAS_TOKEN }}'